steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/images/mdk-app-portfolio:$TAG_NAME', 
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/images/mdk-app-portfolio:$TAG_NAME']

options:
  logging: CLOUD_LOGGING_ONLY